const ChecklistItem = require('../models/ChecklistItem');
const Task = require('../models/Task');
const logger = require('../utils/logger');

/**
 * Generates ChecklistItems (from required documents) and Tasks (from action items)
 * for a processed opportunity.
 *
 * @param {object} opportunity - The mongoose Opportunity document
 * @returns {Promise<{ checklistItems: object[], tasks: object[] }>}
 */
const generateTasksAndChecklist = async (opportunity) => {
  const {
    _id: opportunityId,
    userId,
    requiredDocuments,
    actionItems,
    deadline,
    priority,
    suggestedAssignee,
  } = opportunity;

  logger.info(`[taskService] Generating tasks & checklist for opportunity: ${opportunityId}`);

  // Ensure idempotency: clean up existing checklist items and tasks for this opportunity
  await ChecklistItem.deleteMany({ opportunityId, userId });
  await Task.deleteMany({ opportunityId, userId });

  const checklistData = [];
  const taskData = [];

  // 1. Map required documents to ChecklistItems
  if (Array.isArray(requiredDocuments)) {
    for (const docReq of requiredDocuments) {
      if (docReq && docReq.trim()) {
        checklistData.push({
          opportunityId,
          userId,
          label: docReq.trim(),
          isDocumentRequirement: true,
          checked: false,
        });
      }
    }
  }

  // 2. Map action items to Tasks
  if (Array.isArray(actionItems)) {
    for (const action of actionItems) {
      if (action && action.trim()) {
        taskData.push({
          opportunityId,
          userId,
          title: action.trim(),
          description: '',
          dueDate: deadline || null, // Default to the opportunity's deadline
          priority: priority || 'medium',
          assignee: suggestedAssignee || '', // Free-text assignee assignment
          status: 'todo',
          autoGenerated: true,
        });
      }
    }
  }

  let createdChecklist = [];
  let createdTasks = [];

  if (checklistData.length > 0) {
    createdChecklist = await ChecklistItem.insertMany(checklistData);
    logger.info(`[taskService] Created ${createdChecklist.length} checklist items.`);
  }

  if (taskData.length > 0) {
    createdTasks = await Task.insertMany(taskData);
    logger.info(`[taskService] Created ${createdTasks.length} tasks.`);
  }

  return {
    checklistItems: createdChecklist,
    tasks: createdTasks,
  };
};

module.exports = { generateTasksAndChecklist };
